config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  mount SolidusPaypalBraintree::Engine, at: '/solidus_paypal_braintree'
  mount Ckeditor::Engine => '/ckeditor'
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #   get '/about_us', :to => 'spree/about#index', :as => :about_us
  Spree::Core::Engine.routes.draw do
    namespace :admin do
      filter :locale
      get '/search/countries', to: "search#countries", as: :search_countries
      resources :contact_us_emails do
        member do
          post :clone
        end
      end

      resources :contacts
    end

    resources :contacts

    get '/order_history', to: 'users#order_history', as: 'order_history'

    get '/remove_adjustments', to: 'orders#remove_adjustments', as: 'remove_adjustments'
  end
end

app/models/spree/contact_us_email.rb
require 'discard'

module Spree
  class ContactUsEmail < Spree::Base
    extend FriendlyId
    friendly_id :slug_candidates, use: :history

    acts_as_paranoid
    include Spree::ParanoiaDeprecations

    include Discard::Model
    self.discard_column = :deleted_at

    translates :name, :slug, fallbacks_for_empty_translations: true
    include SolidusGlobalize::Translatable

    has_many :contacts, class_name: 'Spree::Contact', dependent: :destroy

    validates_presence_of :name, :email

    def slug_candidates
      [
        :name
      ]
    end

    def deleted?
      !!deleted_at
    end
    
    def duplicate
      duplicator = ContactUsEmailDuplicator.new(self)
      duplicator.duplicate
    end
  end
end

app/controllers/spree/admin/contact_us_emails_controller.rb
module Spree
  module Admin
    class ContactUsEmailsController < ResourceController
      
      helper_method :clone_object_url

      def index
        session[:return_to] = request.url
        respond_with(@collection)
      end

      def show
        redirect_to action: :edit
      end

      def update
        if @object.update_attributes(permitted_resource_params)
          flash[:success] = flash_message_for(@object, :successfully_updated)
          respond_with(@object) do |format|
            format.html { redirect_to spree.edit_admin_contact_us_email_url }
            format.js   { render layout: false }
          end
        else
          # Stops people submitting blank slugs, causing errors when they try to
          # update the contact_us_email again
          @contact_us_email.slug = @contact_us_email.slug_was if @contact_us_email.slug.blank?
          respond_with(@object)
        end
      end

      def destroy
        @contact_us_email = Spree::ContactUsEmail.friendly.find(params[:id])
        @contact_us_email.discard

        flash[:success] = t('spree.notice_messages.contact_us_email_deleted')

        respond_with(@contact_us_email) do |format|
          format.html { redirect_to collection_url }
          format.js { render_js_for_destroy }
        end
      end

      def clone
        @new = @contact_us_email.duplicate

        if @new.save
          flash[:success] = t('spree.notice_messages.contact_us_email_cloned')
          redirect_to edit_admin_contact_us_email_url(@new)
        else
          flash[:error] = t('spree.notice_messages.contact_us_email_not_cloned', error: @new.errors.full_messages)
          redirect_to admin_contact_us_emails_url
        end
      end

      private
        def find_resource
          Spree::ContactUsEmail.with_deleted.friendly.find(params[:id])
        end

        def collection
          return @collection if @collection
          params[:q] ||= {}
          params[:q][:s] ||= "name asc"
          # @search needs to be defined as this is passed to search_form_for
          @search = super.ransack(params[:q])
          @collection = @search.result.
                order(id: :asc).
                page(params[:page]).per(params[:per_page])
        end

        def clone_object_url(resource)
          clone_admin_contact_us_email_url resource
        end
    end
  end
end

app/helpers/spree/admin/contact_us_emails_helper.rb
module Spree::Admin::ContactUsEmailsHelper
end

app/views/spree/admin/contact_us_emails/_form.html.erb
<div data-hook="admin_contact_us_email_form_fields">

  <div class="row">

    <div class="left col-6" data-hook="admin_contact_us_email_form_left">
      <div data-hook="admin_contact_us_email_form_name">
        <%= f.field_container :name do %>
          <%= f.label :name, class: 'required' %>
          <%= f.text_field :name, class: 'fullwidth title', required: true %>
          <%= f.error_message_on :name %>
        <% end %>
      </div>
    </div>

    <div class="left col-6" data-hook="admin_contact_us_email_form_right">
      <div data-hook="admin_contact_us_email_form_email">
        <%= f.field_container :email do %>
          <%= f.label :email, class: 'required' %>
          <%= f.email_field :email, class: 'fullwidth title', required: true %>
          <%= f.error_message_on :email %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/spree/admin/contact_us_emails/edit.html.erb
<% content_for :page_actions do %>
  <% if can?(:create, Spree::ContactUsEmail) %>
    <li id="new_contact_us_email_link">
      <%= button_link_to t('spree.new_contact_us_email'), new_object_url, { id: 'admin_new_contact_us_email' } %>
    </li>
  <% end %>
<% end %>

<%= render partial: 'spree/shared/error_messages', locals: { target: @contact_us_email } %>

<% admin_breadcrumb(t('spree.contact_us_email_details')) %>

<%= form_for [:admin, @contact_us_email], html: { multipart: true } do |f| %>
  <fieldset class="no-border-top">
    <%= render partial: 'form', locals: { f: f } %>
    <% if can?(:update, @contact_us_email) %>
      <%= render partial: 'spree/admin/shared/edit_resource_links' %>
    <% end %>
  </fieldset>
<% end %>

app/views/spree/admin/contact_us_emails/index.html.erb
<% admin_layout "full-width" %>

<% admin_breadcrumb(plural_resource_name(Spree::ContactUsEmail)) %>

<% content_for :page_actions do %>
  <li id="new_contact_us_email_link">
    <%= button_link_to Spree.t(:new_contact_us_email), new_admin_contact_us_email_path, { :id => 'new_admin_contact_us_email' } %>
  </li>
<% end if can?(:create, Spree::ContactUsEmail) %>

<% content_for :table_filter_title do %>
  <%= Spree.t(:search) %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_contact_us_emails_sidebar">
    <%= search_form_for [:admin, @search] do |f| %>
        <%- locals = {f: f} %>
        <div class="row" data-hook="admin_contact_us_emails_index_search" >
          <div class="col-12">
            <div class="field">
              <%= f.label :name_cont, Spree::ContactUsEmail.human_attribute_name(:name) %>
              <%= f.text_field :name_cont, size: 15 %>
            </div>
          </div>
        </div>

        <div class="actions filter-actions" data-hook="admin_contact_us_emails_index_search_buttons">
          <%= button t('spree.search') %>
        </div>
    <% end %>
  </div>
<% end %>

<div id="new_contact_us_email_wrapper" data-hook></div>

<%= paginate @collection, theme: "solidus_admin" %>

<% if @collection.any? %>
  <table class="index" id="listing_contact_us_emails">
    <colgroup>
       <col style="width: 35%;">
       <col style="width: 35%;">
       <col style="width: 30%;">
    </colgroup>
    <thead>
      <tr data-hook="admin_contact_us_emails_index_headers">
        <th><%= sort_link @search, :name, Spree::ContactUsEmail.human_attribute_name(:name), { default_order: "desc" }, {title: 'admin_contact_us_emails_listing_name_title'} %></th>
        <th><%= Spree::ContactUsEmail.human_attribute_name(:email) %></th>
        <th data-hook="admin_contact_us_emails_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @collection.each do |contact_us_email| %>
          <tr <%== "style='color: red;'" if contact_us_email.deleted? %> id="<%= spree_dom_id contact_us_email %>" data-hook="admin_contact_us_emails_index_rows">
            <td><%= link_to contact_us_email.try(:name), edit_admin_contact_us_email_path(contact_us_email) %></td>
            <td><%= contact_us_email.email %></td>
            <td class="actions" data-hook="admin_contact_us_emails_index_row_actions">
              <%= link_to_edit contact_us_email, no_text: true, class: 'edit' if can?(:edit, contact_us_email) && !contact_us_email.deleted? %>
              &nbsp;
              <%= link_to_clone contact_us_email, no_text: true, class: 'clone' if can?(:clone, contact_us_email) %>
              &nbsp;
              <%= link_to_delete contact_us_email, no_text: true if can?(:delete, contact_us_email) && !contact_us_email.deleted? %>
            </td>
          </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="no-objects-found">
    <%= render 'spree/admin/shared/no_objects_found',
                  resource: Spree::ContactUsEmail,
                  new_resource_url: new_object_url %>
  </div>
<% end %>

<%= paginate @collection, theme: "solidus_admin" %>

app/views/spree/admin/contact_us_emails/new.html.erb
<% admin_breadcrumb link_to(plural_resource_name(Spree::ContactUsEmail), spree.admin_contact_us_emails_path) %>

<% admin_breadcrumb t('spree.new_contact_us_email') %>

<%= render partial: 'spree/shared/error_messages', locals: { target: @contact_us_email } %>

<%= form_for [:admin, @contact_us_email], method: :post, url: admin_contact_us_emails_path, html: { multipart: true } do |f| %>
  <fieldset data-hook="new_contact_us_email">
    <legend align="center"><%= t('spree.new_contact_us_email') %></legend>

    <%= render partial: 'form', locals: { f: f } %>

    <%= render partial: 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>