config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  mount SolidusPaypalBraintree::Engine, at: '/solidus_paypal_braintree'
  mount Ckeditor::Engine => '/ckeditor'
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #   get '/about_us', :to => 'spree/about#index', :as => :about_us
  Spree::Core::Engine.routes.draw do
    namespace :admin do
      filter :locale
      get '/search/countries', to: "search#countries", as: :search_countries
      resources :contact_us_emails do
        member do
          post :clone
        end
      end

      resources :contacts
    end

    resources :contacts

    get '/order_history', to: 'users#order_history', as: 'order_history'

    get '/remove_adjustments', to: 'orders#remove_adjustments', as: 'remove_adjustments'
  end
end

app/models/spree/contact.rb
require 'discard'

module Spree
  class Contact < Spree::Base
    
    acts_as_paranoid
    include Spree::ParanoiaDeprecations

    include Discard::Model
    self.discard_column = :deleted_at

    has_attached_file :file,
                      styles: { mini: '48x48>', email: '150x150>' },
                      default_style: :mini,
                      default_url: 'noimage/:style.png',
                      url: '/spree/contacts/:id/:style/:basename.:extension',
                      path: ':rails_root/public/spree/contacts/:id/:style/:basename.:extension',
                      convert_options: { all: '-strip -auto-orient -colorspace sRGB' }
    
    validates_attachment :file, 
      content_type: { content_type: %w(image/jpeg image/jpg image/png image/gif) }, 
      size: { in: 0..20.megabytes }

    validates_presence_of :name, :email, :subject, :message

    belongs_to :contact_us_email, class_name: 'Spree::ContactUsEmail'

    before_validation :generate_reference_number, on: :create
    after_create :send_email

    def send_email
      if Rails.env.development?
        ContactMailer.notify_email(self).deliver_now
        ContactMailer.acknowledge_email(self).deliver_now
      else  
        ContactMailer.notify_email(self).deliver_later
        ContactMailer.acknowledge_email(self).deliver_later
      end
    end

    def slug_candidates
      [
        :name
      ]
    end

    def deleted?
      !!deleted_at
    end
    
    private 
    
    def generate_reference_number
      prefix = 'GX-ENQ-'
      length = 4
      letters = false
      possible = (0..9).to_a
      possible += ('A'..'Z').to_a if letters

      date = Date.current.strftime("%Y%m%d")
      random = ''
      
      loop do
        # Make a random number.
        random = "#{prefix}#{date}#{(0...length).map { possible.sample }.join}"
        # Use the random number if no other order exists with it.
        if Spree::Contact.exists?(reference_number: random)
          # If over half of all possible options are taken add another digit.
          length += 1 if Spree::Contact.count > (10**length / 2)
        else
          break random
        end
      end
            
      self.reference_number = random
    end
    
  end
end

app/controllers/spree/admin/contacts_controller.rb
module Spree
  module Admin
    class ContactsController < ResourceController
      def index
        session[:return_to] = request.url
        respond_with(@collection)
      end

      def show
        redirect_to action: :edit
      end

      private
        def find_resource
          @contact = Spree::Contact.with_deleted.find(params[:id])
        end

        def collection
          return @collection if @collection
          params[:q] ||= {}
          params[:q][:s] ||= "name asc"
          # @search needs to be defined as this is passed to search_form_for
          @search = super.ransack(params[:q])
          @collection = @search.result.
                order(id: :asc).
                page(params[:page]).per(params[:per_page])
        end
    end
  end
end

app/controllers/spree/contacts_controller.rb
module Spree
  class ContactsController < Spree::StoreController
    def create
      @contact_us = Spree::Contact.new(contact_us_params)

      if @contact_us.save
        flash[:success] = Spree.t('contact_us_success_message')
        redirect_to spree.root_path
      else
        flash[:error] = Spree.t('contact_us_error_message')
        render :'spree/home/index'
      end
    end

    private
      def permitted_review_attributes
        [:contact_us_email_id, :name, :email, :subject, :message, :file]
      end

      def contact_us_params
        params.require(:contact).permit(permitted_review_attributes)
      end

  end
end

app/helpers/spree/admin/contacts_helper.rb
module Spree::Admin::ContactsHelper
end

app/helpers/spree/contacts_helper.rb
module Spree::ContactsHelper
end

app/views/spree/admin/contacts/_form.html.erb
<div data-hook="admin_contact_us_email_form_fields">

  <div class="row">

    <div class="left col-12" data-hook="admin_contact_us_email_form_first">
      <div data-hook="admin_contact_us_email_form_name">
        <%= f.field_container :name do %>
          <%= f.label :name, class: 'required' %>
          <%= f.text_field :name, class: 'fullwidth title', readonly: true %>
          <%= f.error_message_on :name %>
        <% end %>
      </div>
    </div>

    <div class="left col-12" data-hook="admin_contact_us_email_form_second">
      <div data-hook="admin_contact_us_email_form_email">
        <%= f.field_container :email do %>
          <%= f.label :email, class: 'required' %>
          <%= f.email_field :email, class: 'fullwidth title', readonly: true %>
          <%= f.error_message_on :email %>
        <% end %>
      </div>
    </div>

    <div class="left col-12" data-hook="admin_contact_us_email_form_third">
      <div data-hook="admin_contact_us_email_form_subject">
        <%= f.field_container :subject do %>
          <%= f.label :subject, class: 'required' %>
          <%= f.text_field :subject, class: 'fullwidth title', readonly: true %>
          <%= f.error_message_on :subject %>
        <% end %>
      </div>
    </div>
    <div class="left col-12" data-hook="admin_contact_us_email_form_fourth">
      <div data-hook="admin_contact_us_email_form_message">
        <%= f.field_container :message do %>
          <%= f.label :message, class: 'required' %>
          <%= f.text_area :message, class: 'fullwidth title', readonly: true %>
          <%= f.error_message_on :message %>
        <% end %>
      </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-12" data-hook="admin_contact_us_email_form_file">
      <div data-hook="admin_contact_us_email_form_file">
      <% if @contact.file.present? %>  
        <%= f.label :file, class: 'required' %>
        <%= f.field_container :file do %>
          <%= image_tag @contact.file.url(:original) %>
        <% end %>
      <% end %>  
      </div>      
    </div>
  </div>
</div>

app/views/spree/admin/contacts/edit.html.erb
<%= render partial: 'spree/shared/error_messages', locals: { target: @contact_us } %>

<% admin_breadcrumb(t('spree.contact_details')) %>

<% content_for :page_actions do %>
  <li id="new_contact_us_email_link">
    <%= button_link_to Spree.t(:contacts), admin_contacts_path, { :id => 'admin_contacts_email' } %>
  </li>
<% end if can?(:create, Spree::ContactUsEmail) %>

<%= form_for [:admin, @contact], html: { multipart: true } do |f| %>
  <fieldset class="no-border-top">
    <%= render partial: 'form', locals: { f: f } %>

    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= link_to t('spree.actions.cancel'), collection_url, class: 'btn btn-primary' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/contacts/index.html.erb
<% admin_layout "full-width" %>

<% admin_breadcrumb(plural_resource_name(Spree::Contact)) %>

<% content_for :table_filter_title do %>
  <%= Spree.t(:search) %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_contacts_sidebar">
    <%= search_form_for @search, url: admin_contacts_path do |f| %>
        <%- locals = {f: f} %>
        <div class="row" data-hook="admin_contacts_index_search" >
          <div class="col-12">
            <div class="field">
              <%= f.label :name_cont, Spree::Contact.human_attribute_name(:name) %>
              <%= f.text_field :name_cont, size: 15 %>
            </div>
          </div>
        </div>

        <div class="actions filter-actions" data-hook="admin_contacts_index_search_buttons">
          <%= button t('spree.search') %>
        </div>
    <% end %>
  </div>
<% end %>

<div id="new_contact_us_wrapper" data-hook></div>

<%= paginate @collection, theme: "solidus_admin" %>

<% if @collection.any? %>
  <table class="index" id="listing_contacts">
    <colgroup>
       <col style="width: 10%;">
       <col style="width: 20%;">
       <col style="width: 20%;">
       <col style="width: 20%;">
       <col style="width: 30%;">
       <col style="width: 10%;">
    </colgroup>
    <thead>
      <tr data-hook="admin_contacts_index_headers">
        <th><%= sort_link @search, :name, Spree::Contact.human_attribute_name(:name), { default_order: "desc" }, {title: 'admin_contact_us_listing_name_title'} %></th>
        <th><%= Spree::Contact.human_attribute_name(:email) %></th>
        <th><%= Spree::ContactUsEmail.human_attribute_name(:category) %></th>
        <th><%= Spree::Contact.human_attribute_name(:subject) %></th>
        <th><%= Spree::Contact.human_attribute_name(:message) %></th>
        <th><%= Spree::Contact.human_attribute_name(:attachment) %></th>
        <th data-hook="admin_contact_us_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @collection.each do |contact_us| %>
          <tr <%== "style='color: red;'" if contact_us.deleted? %> id="<%= spree_dom_id contact_us %>" data-hook="admin_contacts_index_rows">
            <td><%= contact_us.try(:name) %></td>
            <td><%= contact_us.email %></td>
            <td><%= contact_us.contact_us_email.try(:name) %></td>
            <td><%= contact_us.subject %></td>
            <td><%= truncate(contact_us.message, length: 25, omission: '...') %></td>
            <td><%= image_tag contact_us.file.url(:mini) %></td>
            <td class="actions" data-hook="admin_contact_us_index_row_actions">
              <%= link_to_edit_url edit_admin_contact_url(contact_us), no_text: true, class: 'edit' if can?(:edit, contact_us) && !contact_us.deleted? %>
            </td>
          </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="no-objects-found">
    <%#= render 'spree/admin/shared/no_objects_found',
                  resource: Spree::Contact,
                  new_resource_url: new_object_url %>
  </div>
<% end %>

<%= paginate @collection, theme: "solidus_admin" %>