config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  mount SolidusPaypalBraintree::Engine, at: '/solidus_paypal_braintree'
  mount Ckeditor::Engine => '/ckeditor'
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #   get '/about_us', :to => 'spree/about#index', :as => :about_us
  Spree::Core::Engine.routes.draw do
    namespace :admin do
      filter :locale
      get '/search/countries', to: "search#countries", as: :search_countries
      resources :contact_us_emails do
        member do
          post :clone
        end
      end

      resources :contacts
    end

    resources :contacts

    get '/order_history', to: 'users#order_history', as: 'order_history'

    get '/remove_adjustments', to: 'orders#remove_adjustments', as: 'remove_adjustments'
  end
end

app/models/spree/address_decorator.rb
Spree::Address.class_eval do

  private
  
  def validate_state_matches_country
    if state && country.states_required? && state.country != country
      errors.add(:state, :does_not_match_country)
    end    
  end
  
end

app/models/spree/contact.rb
require 'discard'

module Spree
  class Contact < Spree::Base
    
    acts_as_paranoid
    include Spree::ParanoiaDeprecations

    include Discard::Model
    self.discard_column = :deleted_at

    has_attached_file :file,
                      styles: { mini: '48x48>', email: '150x150>' },
                      default_style: :mini,
                      default_url: 'noimage/:style.png',
                      url: '/spree/contacts/:id/:style/:basename.:extension',
                      path: ':rails_root/public/spree/contacts/:id/:style/:basename.:extension',
                      convert_options: { all: '-strip -auto-orient -colorspace sRGB' }
    
    validates_attachment :file, 
      content_type: { content_type: %w(image/jpeg image/jpg image/png image/gif) }, 
      size: { in: 0..20.megabytes }

    validates_presence_of :name, :email, :subject, :message

    belongs_to :contact_us_email, class_name: 'Spree::ContactUsEmail'

    before_validation :generate_reference_number, on: :create
    after_create :send_email

    def send_email
      if Rails.env.development?
        ContactMailer.notify_email(self).deliver_now
        ContactMailer.acknowledge_email(self).deliver_now
      else  
        ContactMailer.notify_email(self).deliver_later
        ContactMailer.acknowledge_email(self).deliver_later
      end
    end

    def slug_candidates
      [
        :name
      ]
    end

    def deleted?
      !!deleted_at
    end
    
    private 
    
    def generate_reference_number
      prefix = 'GX-ENQ-'
      length = 4
      letters = false
      possible = (0..9).to_a
      possible += ('A'..'Z').to_a if letters

      date = Date.current.strftime("%Y%m%d")
      random = ''
      
      loop do
        # Make a random number.
        random = "#{prefix}#{date}#{(0...length).map { possible.sample }.join}"
        # Use the random number if no other order exists with it.
        if Spree::Contact.exists?(reference_number: random)
          # If over half of all possible options are taken add another digit.
          length += 1 if Spree::Contact.count > (10**length / 2)
        else
          break random
        end
      end
            
      self.reference_number = random
    end
    
  end
end

app/models/spree/contact_us_email.rb
require 'discard'

module Spree
  class ContactUsEmail < Spree::Base
    extend FriendlyId
    friendly_id :slug_candidates, use: :history

    acts_as_paranoid
    include Spree::ParanoiaDeprecations

    include Discard::Model
    self.discard_column = :deleted_at

    translates :name, :slug, fallbacks_for_empty_translations: true
    include SolidusGlobalize::Translatable

    has_many :contacts, class_name: 'Spree::Contact', dependent: :destroy

    validates_presence_of :name, :email

    def slug_candidates
      [
        :name
      ]
    end

    def deleted?
      !!deleted_at
    end
    
    def duplicate
      duplicator = ContactUsEmailDuplicator.new(self)
      duplicator.duplicate
    end
  end
end

app/models/spree/contact_us_email_duplicator.rb
module Spree
  class ContactUsEmailDuplicator
    attr_accessor :contact_us_email

    def initialize(contact_us_email)
      @contact_us_email = contact_us_email
    end

    def duplicate
      new_contact_us_email = duplicate_contact_us_email

      new_contact_us_email
    end

    protected

    def duplicate_contact_us_email
      contact_us_email.dup.tap do |new_contact_us_email|
        new_contact_us_email.name = "COPY OF #{contact_us_email.name}"
        new_contact_us_email.created_at = nil
        new_contact_us_email.deleted_at = nil
        new_contact_us_email.updated_at = nil
        new_contact_us_email.email = contact_us_email.email
      end
    end
  end
end

app/models/spree/editor_setting_decorator.rb
Spree::EditorSetting.class_eval do
  preference :enabled,        :boolean, default: true
  preference :current_editor, :string,  default: 'TinyMCE'
  preference :ids,            :string,  default: 'product_description page_body taxon_description product_translations_attributes_1_description product_translations_attributes_2_description taxon_translations_attributes_1_description taxon_translations_attributes_2_description'

  def self.editors
    %w(TinyMCE CKEditor)
  end
end

app/models/spree/inventory_unit_decorator.rb
Spree::InventoryUnit.class_eval do

  def ensure_can_destroy
    if !backordered? && !on_hand?
      errors.add(:state, :cannot_destroy, state: state)
      throw :abort
    end

    if !shipment.nil?
      if shipment.shipped? || shipment.canceled?
        errors.add(:base, :cannot_destroy_shipment_state, state: shipment.state)
        throw :abort
      end
    end
  end
      
end

app/models/spree/order/date_number_generator.rb
module Spree
  class Order::DateNumberGenerator
    attr_reader :letters, :prefix

    def initialize(options = {})
      @length = options[:length] || Spree::Order::ORDER_NUMBER_LENGTH
      @letters = options[:letters] || Spree::Order::ORDER_NUMBER_LETTERS
      @prefix = options[:prefix] || Spree::Order::ORDER_NUMBER_PREFIX
    end

    def generate
      possible = (0..9).to_a
      possible += ('A'..'Z').to_a if letters
      
      date = DateTime.current.strftime("%Y%m%d")
      
      loop do
        # Make a random number.
        random = "#{prefix}#{date}-#{(0...@length).map { possible.sample }.join}"
        # Use the random number if no other order exists with it.
        if Spree::Order.exists?(number: random)
          # If over half of all possible options are taken add another digit.
          @length += 1 if Spree::Order.count > (10**@length / 2)
        else
          break random
        end
      end
    end
    
  end
end

app/models/spree/order_decorator.rb
Spree::Order.class_eval do

   def finalize!
    # lock all adjustments (coupon promotions, etc.)
    all_adjustments.each(&:finalize!)

    # update payment and shipment(s) states, and save
    updater.update_payment_state
    shipments.each do |shipment|
      shipment.update_state
      shipment.finalize!
    end

    updater.update_shipment_state
    self.email_language_preference = I18n.locale
    save!
    updater.run_hooks

    touch :completed_at

    deliver_order_confirmation_email unless confirmation_delivered?
  end

  def has_personalized_product?
    line_items.each do |item|
      if item.product.is_personalize_product
        return true
      end
    end
    
    return false
  end

  def deliver_order_confirmation_email
    Spree::OrderMailer.confirm_email(self).deliver_later
    Spree::OrderMailer.confirm_email_to_staffs(self).deliver_later
    update_column(:confirmation_delivered, true)
  end
  
  def min_estimated_arrival_date
    order_date = self.completed_at
    delivery_days = self.shipments.first.max_delivery_time
    min_processing_days = 14 # two working weeks
    order_date.advance(days: delivery_days).advance(days: min_processing_days)
  end

  def max_estimated_arrival_date
    order_date = self.completed_at
    delivery_days = self.shipments.first.max_delivery_time
    max_processing_days = 21 # three working weeks
    order_date.advance(days: delivery_days).advance(days: max_processing_days)
  end
  
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  scope :not_personalize_product, -> { where(is_personalize_product: false) }

  add_search_scope :parent_taxon_product do |taxon|
    includes(:classifications).
    where("spree_products_taxons.taxon_id" => taxon.id).
    order(Spree::Classification.arel_table[:position].asc)
  end
  
  add_search_scope :not_personalized do
    where("#{Spree::Product.quoted_table_name}.is_personalize_product = 0")
  end
  
  def display_product_name
    splitted_names = name.split(' ')
    final_name = ''
    temp_name = ''
    splitted_names.each do |token|
      temp_name << "#{token} "
      puts "temp_name ===> #{temp_name} | final_name ====> #{final_name}"
      if temp_name.length > 31
        final_name = "#{final_name.strip}<br>#{token} "
        temp_name = "#{token} "
      else
        final_name << "#{token} "
      end
    end
    return final_name.strip
  end

  def self.to_csv
    CSV.generate do |csv|
      csv << [
        'ID', 
        'Name', 
        'Slug', 
        'Master Price',
        'Cost Price',
        'Available On',
        'Promotionable',
        'SKU',
        'Product Dimension',
        'Shipping Category',
        'Tax Category',
        'Taxons', 
        'Option Types',
        'Meta Title', 
        'Meta Keywords',
        'Meta Description',
        'Product Properties',
        'Created At',
        'Updated At'].flatten
      all.each do |product|
        csv << [product.id, 
          product.try(:name),
          product.slug,
          product.master.try(:price),
          product.try(:cost_price),
          product.try(:available_on), 
          product.try(:promotionable),
          product.sku,
          product.get_product_dimension,
          product.shipping_category.try(:name),
          product.tax_category.try(:name),
          product.get_taxons_name,
          product.get_option_types,
          product.meta_title,
          product.try(:meta_keywords),
          product.meta_description,
          product.get_product_properties,
          product.created_at, 
          product.updated_at
          ].flatten
      end
    end
  end

  def get_product_dimension
    "#{height} x #{width}"
  end

  def get_product_properties
    properties = product_properties.map do |p| 
      "#{p.property.name} : #{p.value}"
    end
    properties.map(&:inspect).join(', ')
  end

  def get_taxons_name
    taxons.map{|taxon| taxon.taxonomy.name}.map(&:inspect).join(',')
  end

  def get_option_types
    option_types.map{|a| a.name}.map(&:inspect).join(',')
  end
end

app/models/spree/product_duplicator_decorator.rb
Spree::ProductDuplicator.class_eval do
            
  protected

  def duplicate_product
    product.dup.tap do |new_product|
      append_number = Time.now.to_i
      I18n.available_locales.each do |locale|
        I18n.with_locale(locale) {
          new_product.name = "#{I18n.t('spree.copy_of')} #{product.name}"
          new_product.slug = product.slug + "-#{append_number}"  
        }
      end
      new_product.taxons = product.taxons
      new_product.created_at = nil
      new_product.deleted_at = nil
      new_product.updated_at = nil
      new_product.product_properties = reset_properties
      new_product.master = duplicate_master
      new_product.variants = product.variants.map { |variant| duplicate_variant variant }
    end
  end

  def duplicate_master
    master = product.master
    master.dup.tap do |new_master|
      new_master.sku = "#{I18n.t('spree.copy_of')} #{master.sku} #{Time.now.to_i}"
      new_master.deleted_at = nil
      new_master.images = master.images.map { |image| duplicate_image image } if @include_images
      new_master.price = master.price
    end
  end
end

app/models/spree/promotion_handler/coupon_decorator.rb
Spree::PromotionHandler::Coupon.class_eval do
  
  def remove
    if promotion.blank?
      set_error_code :coupon_code_not_found
    elsif !promotion_exists_on_order?(order, promotion)
      set_error_code :coupon_code_not_present
    else
      promotion.remove_from(order)
      order.recalculate
      set_success_code :coupon_code_removed
    end

    self    
  end
  
end

app/models/spree/promotion_rule_country.rb
module Spree
  class PromotionRuleCountry < Spree::Base    
    self.table_name = 'spree_promotion_rule_countries'

    belongs_to :promotion_rule, class_name: 'Spree::PromotionRule'
    belongs_to :country
  end
end

app/controllers/spree/admin/contact_us_emails_controller.rb
module Spree
  module Admin
    class ContactUsEmailsController < ResourceController
      
      helper_method :clone_object_url

      def index
        session[:return_to] = request.url
        respond_with(@collection)
      end

      def show
        redirect_to action: :edit
      end

      def update
        if @object.update_attributes(permitted_resource_params)
          flash[:success] = flash_message_for(@object, :successfully_updated)
          respond_with(@object) do |format|
            format.html { redirect_to spree.edit_admin_contact_us_email_url }
            format.js   { render layout: false }
          end
        else
          # Stops people submitting blank slugs, causing errors when they try to
          # update the contact_us_email again
          @contact_us_email.slug = @contact_us_email.slug_was if @contact_us_email.slug.blank?
          respond_with(@object)
        end
      end

      def destroy
        @contact_us_email = Spree::ContactUsEmail.friendly.find(params[:id])
        @contact_us_email.discard

        flash[:success] = t('spree.notice_messages.contact_us_email_deleted')

        respond_with(@contact_us_email) do |format|
          format.html { redirect_to collection_url }
          format.js { render_js_for_destroy }
        end
      end

      def clone
        @new = @contact_us_email.duplicate

        if @new.save
          flash[:success] = t('spree.notice_messages.contact_us_email_cloned')
          redirect_to edit_admin_contact_us_email_url(@new)
        else
          flash[:error] = t('spree.notice_messages.contact_us_email_not_cloned', error: @new.errors.full_messages)
          redirect_to admin_contact_us_emails_url
        end
      end

      private
        def find_resource
          Spree::ContactUsEmail.with_deleted.friendly.find(params[:id])
        end

        def collection
          return @collection if @collection
          params[:q] ||= {}
          params[:q][:s] ||= "name asc"
          # @search needs to be defined as this is passed to search_form_for
          @search = super.ransack(params[:q])
          @collection = @search.result.
                order(id: :asc).
                page(params[:page]).per(params[:per_page])
        end

        def clone_object_url(resource)
          clone_admin_contact_us_email_url resource
        end
    end
  end
end

app/controllers/spree/admin/contacts_controller.rb
module Spree
  module Admin
    class ContactsController < ResourceController
      def index
        session[:return_to] = request.url
        respond_with(@collection)
      end

      def show
        redirect_to action: :edit
      end

      private
        def find_resource
          @contact = Spree::Contact.with_deleted.find(params[:id])
        end

        def collection
          return @collection if @collection
          params[:q] ||= {}
          params[:q][:s] ||= "name asc"
          # @search needs to be defined as this is passed to search_form_for
          @search = super.ransack(params[:q])
          @collection = @search.result.
                order(id: :asc).
                page(params[:page]).per(params[:per_page])
        end
    end
  end
end

app/controllers/spree/admin/locale_controller_decorator.rb
# frozen_string_literal: true

module Spree
  module Admin
    class LocaleController < Spree::Admin::BaseController
      def set
        locale = params[:switch_to_locale].to_s.presence

        if locale && I18n.available_locales.include?(locale.to_sym)
          I18n.locale = locale
          session[:locale] = locale

          respond_to do |format|
            format.json { render json: { locale: locale, location: spree.admin_url + request.referrer.split("admin")[1] } }
          end
        else
          respond_to do |format|
            format.json { render json: { locale: I18n.locale }, status: 404 }
          end
        end
      end
    end
  end
end

app/controllers/spree/admin/products_controller_decorator.rb
module Spree
  module Admin
    class ProductsController < ResourceController
      
      def index
        session[:return_to] = request.url
        respond_to do |format|
          format.html
          format.csv { send_data @collection.except(:limit, :offset).to_csv, filename: "products-#{DateTime.now}.csv" }
        end
      end
    end
  end
end

app/views/spree/users/_edit_form.html.erb
<%#= render partial: 'spree/shared/error_messages', locals: { target: @user } %>
<div class="row">
  <div class="col-lg-5">
    <div class="subsection" id="edit-account">
      <div data-hook="account_edit">
        <%= form_for Spree::User.new, as: @user, url: spree.user_path(@user), method: :put do |f| %>
          <%= render partial: 'spree/shared/user_form', locals: { f: f } %>
          <p>
            <%= f.submit Spree.t(:update), class: 'btn btn-info' %>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/spree/users/_order_summary.html.erb
<% if @user_orders.present? %>
  <% @user_orders.each do |order| %>
    <div class="row">
      <div class="col-lg-5">
        <div class="subsection">
          <div class="order-details-card">
            <h3 class="fw900 text-uppercase"><%= t("order.order_number") %>: <%= order.number %></h3>
            <div class="columns order-confirm-address alpha four" data-hook="order-ship-address">
              <%= render partial: 'spree/shared/address', locals: { address: order.ship_address, type: "shipping", order: order } %>
              <%= render partial: 'spree/shared/address', locals: { address: order.bill_address, type: "billing", order: order } %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-7">
        <div class="table-responsive">
          <table class="table table-hover" style="min-width: 500px">
            <thead>
              <tr>
                <th scope="col"></th>
                <th scope="col" class="text-uppercase"><%= Spree.t(:sub_total) %></th>
              </tr>
            </thead>
            <tbody>
                <% order.line_items.each do |item| %>
                  <tr>
                    <td>
                      <div class="row">
                        <div class="col-3">
                          <div data-hook="order_item_image">
                            <% if item.variant.images.empty? %>
                              <%= link_to(render('spree/shared/image', image: item.variant.product.display_image, size: :small), item.variant.product, class: 'order-img') %>
                            <% else %>
                              <div class="product-img ">
                                <%= link_to(render('spree/shared/image', image: item.variant.images.first, size: :small), item.variant.product, class: 'order-img') %>
                              </div>
                            <% end %>
                          </div>
                        </div>
                        <div class="col">
                          <div data-hook="order_item_description">
                            <h4 class="fw900 text-uppercase"><%= item.variant.product.name %></h4>
                          </div>
                        </div>
                      </div>
                    </td>
                    <td data-hook="order_item_total" class="total"><span><%= item.display_amount.to_html %></span></td>
                  </tr>
                <% end %>

                <tbody id='shipment-total'>
                  <% order.shipments.group_by { |s| s.selected_shipping_rate.name }.each do |name, shipments| %>
                    <tr class="total" data-hook='shipment-row'>
                      <td><i class="fa fa-truck mr-2 text-primary" aria-hidden="true"></i><%= t('spree.shipping') %>: <strong><%= name %></strong></td>
                      <td class="total"><span><%= Spree::Money.new(shipments.sum(&:total_before_tax), currency: order.currency).to_html %></span></td>
                    </tr>
                  <% end %>
                </tbody>

                <tfoot class="subsection">
                  <tr>
                    <td colspan="2">
                      <div class="row m-0">
                        <div class="col-lg-12">
                          <div class="row">
                            <div class="col-6">
                              <p class="fw900"><%= t('spree.total') %>:</p>
                            </div>
                            <div class="col-3 offset-3">
                              <p class="" id="order_total"><%= order.display_order_total_after_store_credit.to_html %></p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </td>
                  </tr>
                </tfoot>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <hr>
  <% end %>
<% end %>

app/views/spree/users/edit.js.erb
$('.order_summary').html('');
$('.order_summary').html("<div class='col-md-9'><h2 class='fw900 text-primary text-uppercase'><%= Spree.t(:edit_profile) %></h2><%= escape_javascript (render partial: 'edit_form') %></div>");

app/views/spree/users/order_history.js.erb
$('.order_summary').html('');
$('.order_summary').html("<div class='col-md-9'><h2 class='fw900 text-primary text-uppercase'><%= Spree.t(:order_history) %></h2><%= escape_javascript (render partial: 'order_summary') %></div>");

app/views/spree/users/show.html.erb
<div class="main">
  <section class="section account-section">
    <div class="container bigger">
      <div class="row">
        <div class="col-md-3">
          <div class="account-box">
            <h2 class="text-primary account-box-title"><%= accurate_title %></h2>
            <ul class="account-nav">
              <li>
                <%= link_to Spree.t(:current_order), account_path %>
              </li>
              <li>
                <%= link_to Spree.t(:shopping_cart), cart_path %>
              </li>
              <li>
                <%= link_to Spree.t(:order_history), order_history_path, remote: true %>
              </li>
              <li>
                <div data-hook="account_summary" class="account-summary">
                  <dl id="user-info">
                    <dd><%= link_to Spree.t(:edit_profile), spree.edit_account_path, remote: true %></dd>
                  </dl>
                </div>
              </li>
            </ul>
          </div>
        </div>

        <div class="order_summary col-md-9">
          <h2 class="fw900 text-primary text-uppercase"><%= Spree.t(:current_order_summary) %></h2>
          <%= render partial: 'order_summary' %>
        </div>
      </div>
    </div>
  </section>
</div>